### ISSUE TITLE
Colision with Place Footrpints action plugin

### ISSUE THREAD

**Issue by MitjaNemec** [yaqwsx/pcbnewTransition#2]
Hi, a used (@codeman256) had an [issue](https://github.com/MitjaNemec/PlaceFootprints/issues/14) running my plugin (Place Footprints). Looking at the log file it seems that pcbnewTransition has an effect also on plugins that don't use it.

**Comment by yaqwsx** [comment]
This should be already resolved in eb27d4b6c640034e0a600372c8da35b7a63038d2 (and it is already released).

**Comment by MitjaNemec** [comment]
Thanks for the prompt response.
