### ISSUE TITLE
Still breaks pcbnew module

### ISSUE THREAD

**Issue by qu1ck** [yaqwsx/pcbnewTransition#3]
I had a wild chase figuring this out with TransformIt plugin user.

This package still breaks other plugins:

![image](https://user-images.githubusercontent.com/3622532/233503262-9ddfbbd3-56c9-4eb9-a61d-41e53ca80e2c.png)

I don't quite understand why but isinstance() stops working to check object types.

**Comment by FrightRisk** [comment]
Hello, I am having the same issue. Could you take a look at this. Happy to help provide logs to help, but something in this great KiKat tool is breaking other plugins, in particular "Transformit". So I have to keep Kicat uninstalled until I need to use it and then re-install it. Thanks!

**Comment by tormyvancool** [comment]
yes I still have the issue on the 7.0.6. We need to be able to use something to resize imported images. Normally are Logos or instructions right printed on the silk-layer

**Comment by a-allard** [comment]
Hi @yaqwsx,

I ended up having the same issue in Kicad on Windows and Ubuntu.  I originally thought it was with a different plugin then with KiCad itself.

* [Other pluing issue](https://github.com/Steffen-W/KiCad-Parasitics/issues/5)
* [Kicad issue](https://gitlab.com/kicad/code/kicad/-/issues/15943)

I got around this by uninstalling the [KiKit plugin](https://github.com/yaqwsx/KiKit).

I am running Kicad 7.0.8.  It would be really nice it this were to be fixed.

I don't know why this is happening but it is frustrating...

**Comment by a-allard** [comment]
> Hi @yaqwsx,
> 
> I ended up having the same issue in Kicad on Windows and Ubuntu. I originally thought it was with a different plugin then with KiCad itself.
> 
> * [Other pluing issue](https://github.com/Steffen-W/KiCad-Parasitics/issues/5)
> * [Kicad issue](https://gitlab.com/kicad/code/kicad/-/issues/15943)
> 
> I got around this by uninstalling the [KiKit plugin](https://github.com/yaqwsx/KiKit).
> 
> I am running Kicad 7.0.8. It would be really nice it this were to be fixed.
> 
> I don't know why this is happening but it is frustrating...

Nevermind......  Updating the KiKit backend `pip install -U kikit` solved my issue.  Sorry about that.

**Comment by tormyvancool** [comment]
> > Hi @yaqwsx,
> > I ended up having the same issue in Kicad on Windows and Ubuntu. I originally thought it was with a different plugin then with KiCad itself.
> > 
> > * [Other pluing issue](https://github.com/Steffen-W/KiCad-Parasitics/issues/5)
> > * [Kicad issue](https://gitlab.com/kicad/code/kicad/-/issues/15943)
> > 
> > I got around this by uninstalling the [KiKit plugin](https://github.com/yaqwsx/KiKit).
> > I am running Kicad 7.0.8. It would be really nice it this were to be fixed.
> > I don't know why this is happening but it is frustrating...
> 
> Nevermind...... Updating the KiKit backend `pip install -U kikit` solved my issue. Sorry about that.

Not to me.

**Comment by a-allard** [comment]
> > Hi @yaqwsx,
> > I ended up having the same issue in Kicad on Windows and Ubuntu. I originally thought it was with a different plugin then with KiCad itself.
> > 
> > * [Other pluing issue](https://github.com/Steffen-W/KiCad-Parasitics/issues/5)
> > * [Kicad issue](https://gitlab.com/kicad/code/kicad/-/issues/15943)
> > 
> > I got around this by uninstalling the [KiKit plugin](https://github.com/yaqwsx/KiKit).
> > I am running Kicad 7.0.8. It would be really nice it this were to be fixed.
> > I don't know why this is happening but it is frustrating...
> 
> Nevermind...... Updating the KiKit backend `pip install -U kikit` solved my issue. Sorry about that.

Interestingly enough.  This solved the issue on MS windows.  But not on ubuntu 22.04.  I had to `pip uninstall -y kikit` for kicad to work.  Frustrating I will need to reinstall kikit when I want to panelize pcbs....

**Comment by tormyvancool** [comment]
> > > Hi @yaqwsx,
> > > I ended up having the same issue in Kicad on Windows and Ubuntu. I originally thought it was with a different plugin then with KiCad itself.
> > > 
> > > * [Other pluing issue](https://github.com/Steffen-W/KiCad-Parasitics/issues/5)
> > > * [Kicad issue](https://gitlab.com/kicad/code/kicad/-/issues/15943)
> > > 
> > > I got around this by uninstalling the [KiKit plugin](https://github.com/yaqwsx/KiKit).
> > > I am running Kicad 7.0.8. It would be really nice it this were to be fixed.
> > > I don't know why this is happening but it is frustrating...
> > 
> > 
> > Nevermind...... Updating the KiKit backend `pip install -U kikit` solved my issue. Sorry about that.
> 
> Interestingly enough. This solved the issue on MS windows. But not on ubuntu 22.04. I had to `pip uninstall -y kikit` for kicad to work. Frustrating I will need to reinstall kikit when I want to panelize pcbs....

So, ti's not sufficient to uninstall kikit but you must give the command line instruction?
I'm on W11 and to be honest it doesn't work the first solution was working for you

**Comment by a-allard** [comment]
On Windows 11 I uninstalled the kikit plugin and the backend with pip, restarted kicad.  Checked it to see kicad was working correctly.  Reinstalled KiKit backend via pip.  Then resinstalled the KiKit plugin and restarted KiCad again.  It seemed to work on KiCad in Windows 11.

**Comment by tormyvancool** [comment]
Tested on KiCAD 8.0.0 it still not working

**Comment by a-allard** [comment]
Yeah.  I actually gave up using any kicad plugging that uses this pcbnewtransision.  It breaks all other plugins so until pcbnewtransision goes away I'm done with kikit.  Sad as it is a really useful plugin.  But until it stops breaking all other plugins I'm done.

**Comment by yaqwsx** [comment]
Since we support only the two most-recent releases of KiCAD, we can revert the fix of #2. Released as https://github.com/yaqwsx/pcbnewTransition/releases/tag/v0.4.1

**Comment by FrightRisk** [comment]
Not sure what you mean by revert, but this is still broken in Kicad 8. I can't resize anything with Transform It if KiKit is installed

**Comment by yaqwsx** [comment]
Could you confirm that you have [v0.4.1 (release)](https://github.com/yaqwsx/pcbnewTransition/releases/tag/v0.4.1) installed?
