### ISSUE TITLE
Could we get a pypi release with Python 3.12 support?

### ISSUE THREAD

**Issue by jfly** [yaqwsx/pcbnewTransition#7]
I see https://github.com/yaqwsx/pcbnewTransition/issues/6, and I can confirm that https://github.com/yaqwsx/pcbnewTransition/commit/c01829807de18cddc6d735d04bab5fafa67dd95f works for me.

However, there hasn't been a release of pcbnewTransition with that fix yet. Any chance we could get it released?

**Comment by yaqwsx** [comment]
Done.

**Comment by jfly** [comment]
Thanks, @yaqwsx! This makes the work I'm doing over in https://github.com/NixOS/nixpkgs/pull/336124 a little cleaner =)
